### ISSUE TITLE
Set up helm repository

### ISSUE THREAD

**Issue by andrenarchy** [satoshipay/stellar-helm-charts#8]
Cloning this repository and running `helm install/update` with the local files is fine for testing – for making people's lives easier we should host a helm repository.

Note: I tried publishing the charts in https://github.com/helm/charts/tree/master/stable/ (and you can actually find [an outdated core](https://github.com/helm/charts/tree/master/stable/stellar-core) there)  but the response time is terrible and I'd rather move fast with a self-hosted repository.

**Comment by todkap** [comment]
Quick share that I forgot to mention earlier.  IBM has leveraged Github to host their helm charts (https://github.com/IBM/charts).  This removes some of the barriers to getting chart updates merged.  It is really easy on the CLI to add another chart repo.   Might be a good compromise for satoshipay.

**Comment by todkap** [comment]
This may be receiving more focus now. https://github.com/helm/charts/pull/10661#issuecomment-501138522 .  I wonder if we should open a new github issue with links to the article and proposal to contribute these helm charts to the public helm repo.

Otherwise, users can just add our github repo as another helm chart repo to scan for charts and install from there.  The only sticking point in any of these solutions is that they need to have local copies values.yaml that does the overrides for their env.  I have not tried to specify the values.yaml as a URL when passing it to helm install.

**Comment by alinnow** [comment]
Now available at https://satoshipay.github.io/stellar-helm-charts/ (will 404, see https://satoshipay.github.io/stellar-helm-charts/index.yaml instead)

**Comment by alinnow** [comment]
@andrenarchy for future updates, bump chart versions as appropriate and run publish.sh. I didn't set up any CI for this
